# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TicketApp' do
 
  use_frameworks!
	pod 'SnapKit'
	pod 'Alamofire', '~> 4.0.1’
   	pod 'SwiftyJSON'
	pod 'SVProgressHUD','1.1.3'
	pod 'YYModel'
	pod 'pop'
	pod 'YYText'
	pod 'MJRefresh'
    pod 'MWPhotoBrowser'
    pod 'AFNetworking'
    pod 'SDWebImage'
    
  target 'TicketAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TicketAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
