# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TicketApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'SnapKit', '~> 3.0.0’
	pod 'Alamofire', '~> 4.0.1’
    pod ‘SwiftyJSON’
	pod 'SDWebImage'
	pod 'SVProgressHUD','1.1.3'
	pod 'YYModel'
	pod 'pop'
	pod 'YYText'
  # Pods for TicketApp

  target 'TicketAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TicketAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
